[package]
name = "tmtc-linux-ground"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.45.0"
serde = { version= "1.0.228", features = ["derive"] }
serde_cbor = "0.11.2"
simple_config = { git = "https://github.com/Eleocraft/simple_config_rs.git" }
south-common = { version = "0.2.0", git = "ssh://git@github.com/S2outh/south-common.git" }
tokio = { version = "1.48.0", features = [ "rt-multi-thread", "macros" ] }
